### ISSUE TITLE
JsonWebTokenError: jwt malformed

### ISSUE THREAD

**Issue by ghost** [arpanp11/help-desk-mern#4]
get a jwt malformed on backend when trying to create a ticket 
at Object.module.exports [as verify] (\help-desk-mern-main\node_modules\jsonwebtoken\verify.js:63:17)
    at \help-desk-mern-main\backend\middleware\authMiddleware.js:17:27
    at asyncUtilWrap (\help-desk-mern-main\node_modules\express-async-handler\index.js:3:20)
    at Layer.handle [as handle_request] (\help-desk-mern-main\node_modules\express\lib\router\layer.js:95:5)
    at next (\help-desk-mern-main\node_modules\express\lib\router\route.js:137:13)
    at next (\help-desk-mern-main\node_modules\express\lib\router\route.js:131:14)
    at next (\help-desk-mern-main\node_modules\express\lib\router\route.js:131:14)
    at Route.dispatch (\help-desk-mern-main\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (\help-desk-mern-main\node_modules\express\lib\router\layer.js:95:5)

**Comment by arpanp11** [comment]
fixed create a ticket issue #4
